/* opxx(a,b) OP##a is the enumerate no of operator b */
opxx(PLUS, " + " )
opxx(MINUS, " - ")
opxx(MULT, " * ")
opxx(DIV, " / ")
opxx(EQ, " = ")
opxx(EQEQ, " == ")
opxx(NOTEQ, " != ")
opxx(LT, " < ")
opxx(GT, " > ")
opxx(LTEQ, " <= ")
opxx(GTEQ, " >= ")
opxx(ANDAND, " && ")
opxx(OROR, " || ")
opxx(NOT, " ! ")
opxx(MOD, " % ")

